name: 🔄 Run GSheet Update

on:
  workflow_dispatch:    # Manual trigger via GitHub UI
  schedule:
    - cron: '30 3 * * 1-5'   # Mon–Fri, 9:00 AM IST (3:30 AM UTC)

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    env:
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      GSHEET_CRED_B64: ${{ secrets.GSHEET_CRED_B64 }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
      ANGEL_CLIENT_CODE: ${{ secrets.ANGEL_CLIENT_CODE }}
      ANGEL_CLIENT_PWD: ${{ secrets.ANGEL_CLIENT_PWD }}
      ANGEL_TOTP_SECRET: ${{ secrets.ANGEL_TOTP_SECRET }}

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          pip install gspread oauth2client requests

      - name: 🔐 Export environment variables from secrets (safe)
        run: |
          {
            echo "GSHEET_CRED_B64<<EOF"
            echo "${{ secrets.GSHEET_CRED_B64 }}"
            echo "EOF"
            echo "GSHEET_ID=${{ secrets.GSHEET_ID }}"
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}"
            echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}"
            echo "ANGEL_API_KEY=${{ secrets.ANGEL_API_KEY }}"
            echo "ANGEL_CLIENT_CODE=${{ secrets.ANGEL_CLIENT_CODE }}"
            echo "ANGEL_CLIENT_PWD=${{ secrets.ANGEL_CLIENT_PWD }}"
            echo "ANGEL_TOTP_SECRET=${{ secrets.ANGEL_TOTP_SECRET }}"
          } >> $GITHUB_ENV

      - name: ▶️ Run main.py
        run: python main.py
