name: ЁЯУИ Auto Trading Bot

on:
  push:                        # рдЬрдм рднреА рдЖрдк рдХреБрдЫ GitHub рдкрд░ push рдХрд░реЗрдВ
  workflow_dispatch:          # рдЬрдм рднреА рдЖрдк рдореИрдиреНрдпреБрдЕрд▓реА "Run workflow" рджрдмрд╛рдПрдВ
  schedule:
    - cron: '*/30 * * * *'    # рд╣рд░ 30 рдорд┐рдирдЯ рдореЗрдВ auto-run (UTC рдЯрд╛рдЗрдо)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      GSHEET_CRED_B64: ${{ secrets.GSHEET_CRED_B64 }}
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
      ANGEL_CLIENT_CODE: ${{ secrets.ANGEL_CLIENT_CODE }}
      ANGEL_CLIENT_PWD: ${{ secrets.ANGEL_CLIENT_PWD }}
      ANGEL_TOTP_SECRET: ${{ secrets.ANGEL_TOTP_SECRET }}

    steps:
      - name: ЁЯУе Checkout Repo
        uses: actions/checkout@v4

      - name: ЁЯРН Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ЁЯУж Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install smartapi-python

      - name: ЁЯФР Export Env Variables
        run: |
          echo "GSHEET_CRED_B64=${{ secrets.GSHEET_CRED_B64 }}" >> $GITHUB_ENV
          echo "GSHEET_ID=${{ secrets.GSHEET_ID }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV
          echo "ANGEL_API_KEY=${{ secrets.ANGEL_API_KEY }}" >> $GITHUB_ENV
          echo "ANGEL_CLIENT_CODE=${{ secrets.ANGEL_CLIENT_CODE }}" >> $GITHUB_ENV
          echo "ANGEL_CLIENT_PWD=${{ secrets.ANGEL_CLIENT_PWD }}" >> $GITHUB_ENV
          echo "ANGEL_TOTP_SECRET=${{ secrets.ANGEL_TOTP_SECRET }}" >> $GITHUB_ENV

      - name: ЁЯЪА Run Bot
        run: python main.py
